### ISSUE TITLE
don't use --lines

### ISSUE THREAD

**Issue by stevengj** [JaredCrean2/PETSc.jl#10]
In your `install_petsc.sh` shell script (which would ideally disappear in favor of a pure Julia script), you are using `tail --lines=X` and `head --lines=X`.  `--lines=X` is a GNU-ism that is not POSIX, e.g. it is not supported in the BSD `head` and `tail` used on OSX.   Use `-n X` instead.

**Comment by andreasnoack** [comment]
I still can't build on OSX because of this.

**Comment by JaredCrean2** [comment]
Thanks for the reminder, should be fixed now (I don't have a non GNU environment to test in, so please confirm this).

**Comment by andreasnoack** [comment]
Yes. It works now. Thanks.
