### ISSUE TITLE
wrap multiple PETSc libraries (float, double, complex, ...)

### ISSUE THREAD

**Issue by stevengj** [JaredCrean2/PETSc.jl#6]
I know that we plan to do this eventually, and there is some untested skeleton code for this already, but it would be good to get started on this for real, because retro-fitting this might otherwise become more and more painful.

**Comment by stevengj** [comment]
e.g. `PetscInitialize()` currently initializes only the `Float64` version.  Is it even possible to call `PetscInitialize` for multiple Petsc versions in the same program?

**Comment by stevengj** [comment]
Probably `src/generated` should have subdirectories `Float64`, `Complex128`, etcetera, containing the respective copies of the Clang-generated files.

**Comment by JaredCrean2** [comment]
All three are wrapped and being tested as of d8bfbd4a11793f62ece44810cedeec2f9dbef41f
